apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafka-test-apps
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 86400000
      segment.bytes: 1073741824
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: scholzj/quarkus-kafka-producer:latest
        env:
          - name: MP_MESSAGING_OUTGOING_PRODUCED_BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: MP_MESSAGING_OUTGOING_PRODUCED_TOPIC
            value: kafka-test-apps
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: scholzj/quarkus-kafka-consumer:latest
        env:
          - name: MP_MESSAGING_INCOMING_CONSUMED_BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: MP_MESSAGING_INCOMING_CONSUMED_TOPIC
            value: kafka-test-apps
          - name: MP_MESSAGING_INCOMING_CONSUMED_GROUP_ID
            value: my-kafka-consumer
